# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.setFixedSize(750, 447)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("border : 1px solid")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.puList = QtWidgets.QComboBox(self.centralwidget)
        self.puList.setGeometry(QtCore.QRect(70, 70, 171, 21))
        self.puList.setObjectName("puList")
        self.duList = QtWidgets.QComboBox(self.centralwidget)
        self.duList.setGeometry(QtCore.QRect(300, 70, 171, 21))
        self.duList.setCurrentText("")
        self.duList.setObjectName("duList")
        self.accountsList = QtWidgets.QComboBox(self.centralwidget)
        self.accountsList.setGeometry(QtCore.QRect(530, 70, 171, 21))
        self.accountsList.setObjectName("accountsList")
        self.fileLocation = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLocation.setGeometry(QtCore.QRect(70, 140, 401, 20))
        self.fileLocation.setStyleSheet("padding-left : 5px")
        self.fileLocation.setReadOnly(True)
        self.fileLocation.setObjectName("fileLocation")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(530, 140, 171, 23))
        self.browseButton.setStyleSheet("background-color : yellow")
        self.browseButton.setObjectName("browseButton")
        self.generateReportButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateReportButton.setGeometry(QtCore.QRect(260, 200, 291, 23))
        self.generateReportButton.setStyleSheet("background-color : yellow")
        self.generateReportButton.setObjectName("generateReportButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 270, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.reportFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.reportFileName.setGeometry(QtCore.QRect(200, 270, 401, 20))
        self.reportFileName.setStyleSheet("padding-left : 5px")
        self.reportFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.reportFileName.setReadOnly(True)
        self.reportFileName.setObjectName("reportFileName")
        self.downloadReport = QtWidgets.QRadioButton(self.centralwidget)
        self.downloadReport.setGeometry(QtCore.QRect(190, 330, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.downloadReport.setFont(font)
        self.downloadReport.setChecked(True)
        self.downloadReport.setObjectName("downloadReport")
        self.emailReport = QtWidgets.QRadioButton(self.centralwidget)
        self.emailReport.setGeometry(QtCore.QRect(390, 330, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.emailReport.setFont(font)
        self.emailReport.setObjectName("emailReport")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(540, 390, 171, 23))
        self.downloadButton.setStyleSheet("background-color : yellow")
        self.downloadButton.setObjectName("downloadButton")
        self.emaiInput = QtWidgets.QLineEdit(self.centralwidget)
        self.emaiInput.setGeometry(QtCore.QRect(80, 390, 401, 20))
        self.emaiInput.setStyleSheet("padding-left : 5px")
        self.emaiInput.setReadOnly(True)
        self.emaiInput.setObjectName("emaiInput")
        self.MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(self.MainWindow)
        self.duList.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

        self.setupClicks()

    def setupClicks(self):
        self.browseButton.clicked.connect(self.browse)

    def browse(self):
        dialog = QFileDialog()
        
        fname = dialog.getOpenFileName(None, "Select File", "", "Log files (*.log)")

        print(fname)
                    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "RBA"))
        self.label.setText(_translate("MainWindow", "RBA Report Generator"))
        self.fileLocation.setText(_translate("MainWindow", "Browse log file......"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.generateReportButton.setText(_translate("MainWindow", "Generate Report"))
        self.label_2.setText(_translate("MainWindow", "Utilization Report"))
        self.reportFileName.setText(_translate("MainWindow", "File name here"))
        self.downloadReport.setText(_translate("MainWindow", "Download Report"))
        self.emailReport.setText(_translate("MainWindow", "Email Report"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.emaiInput.setText(_translate("MainWindow", "File Location"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.MainWindow.show()
    sys.exit(app.exec_())