# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(80, 147, 255)")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("padding-left : 5px;\n"
"background-color:gold;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.puList = QtWidgets.QComboBox(self.centralwidget)
        self.puList.setGeometry(QtCore.QRect(70, 70, 171, 21))
        self.puList.setStyleSheet("background-color:white;\n"
"color:black;\n"
"border : 2px solid white;\n"
"border-radius : 3px\n"
"")
        self.puList.setCurrentText("")
        self.puList.setObjectName("puList")
        self.duList = QtWidgets.QComboBox(self.centralwidget)
        self.duList.setGeometry(QtCore.QRect(300, 70, 171, 21))
        self.duList.setStyleSheet("background-color:white;\n"
"color:black;\n"
"border : 2px solid white;\n"
"border-radius : 3px\n"
"")
        self.duList.setCurrentText("")
        self.duList.setObjectName("duList")
        self.accountsList = QtWidgets.QComboBox(self.centralwidget)
        self.accountsList.setGeometry(QtCore.QRect(530, 70, 171, 21))
        self.accountsList.setStyleSheet("background-color:white;\n"
"color:black;\n"
"border : 2px solid white;\n"
"border-radius : 3px\n"
"")
        self.accountsList.setObjectName("accountsList")
        self.fileLocation = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLocation.setGeometry(QtCore.QRect(70, 140, 401, 31))
        self.fileLocation.setStyleSheet("padding-left : 5px;\n"
"background-color:white;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.fileLocation.setText("")
        self.fileLocation.setReadOnly(True)
        self.fileLocation.setObjectName("fileLocation")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(530, 140, 171, 31))
        self.browseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browseButton.setStyleSheet("padding-left : 5px;\n"
"background-color:gold;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.browseButton.setObjectName("browseButton")
        self.generateReportButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateReportButton.setGeometry(QtCore.QRect(260, 200, 291, 31))
        self.generateReportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateReportButton.setStyleSheet("padding-left : 5px;\n"
"background-color:gold;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.generateReportButton.setObjectName("generateReportButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.reportFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.reportFileName.setGeometry(QtCore.QRect(200, 270, 401, 31))
        self.reportFileName.setStyleSheet("padding-left : 5px;\n"
"background-color:white;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.reportFileName.setText("")
        self.reportFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.reportFileName.setReadOnly(True)
        self.reportFileName.setObjectName("reportFileName")
        self.downloadReport = QtWidgets.QRadioButton(self.centralwidget)
        self.downloadReport.setGeometry(QtCore.QRect(190, 330, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.downloadReport.setFont(font)
        self.downloadReport.setChecked(True)
        self.downloadReport.setObjectName("downloadReport")
        self.emailReport = QtWidgets.QRadioButton(self.centralwidget)
        self.emailReport.setGeometry(QtCore.QRect(390, 330, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.emailReport.setFont(font)
        self.emailReport.setObjectName("emailReport")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(540, 382, 171, 31))
        self.downloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadButton.setStyleSheet("padding-left : 5px;\n"
"background-color:gold;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.downloadButton.setObjectName("downloadButton")
        self.emailInput = QtWidgets.QLineEdit(self.centralwidget)
        self.emailInput.setGeometry(QtCore.QRect(80, 379, 401, 31))
        self.emailInput.setToolTip("")
        self.emailInput.setStyleSheet("padding-left : 5px;\n"
"background-color:white;\n"
"color:black;\n"
"border: 2px solid white;\n"
"border-radius : 5px")
        self.emailInput.setText("")
        self.emailInput.setReadOnly(True)
        self.emailInput.setObjectName("emailInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.duList.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RBA"))
        self.label.setText(_translate("MainWindow", "RBA Report Generator"))
        self.fileLocation.setPlaceholderText(_translate("MainWindow", "Browse log file......"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.generateReportButton.setText(_translate("MainWindow", "Generate Report"))
        self.label_2.setText(_translate("MainWindow", "Utilization Report"))
        self.reportFileName.setPlaceholderText(_translate("MainWindow", "File name here"))
        self.downloadReport.setText(_translate("MainWindow", "Download Report"))
        self.emailReport.setText(_translate("MainWindow", "Email Report"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.emailInput.setPlaceholderText(_translate("MainWindow", "File Location"))
